# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1f430d97b3a8b925c2d699f710e49d2cefbed2cec80367efffe8d86d8709f1cfada339dce801b0a7653da46a152d06897ccff21a207081f2a63eb45292cec02

test:
  secret_key_base: a6be5e4fedaaf966a46e5f2688f7ac99a1c588f5e8b10b16987c4722848e65fb958cf5fe4588bfd9901efd0f4b67c8cf8a9b076576531f8b335a330f40cb21fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
